name: Smoke Test

on:
  workflow_dispatch:

concurrency:
  group: smoke-test
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: Swatinem/rust-cache@v2.7.0
      - run: cargo build --manifest-path crates_io_smoke_test/Cargo.toml
      - run: cargo run --manifest-path crates_io_smoke_test/Cargo.toml --quiet
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.STAGING_SMOKE_TEST_TOKEN }}
